### ISSUE TITLE
libnvme openssl meson subproject compilation fails

### ISSUE THREAD

**Issue by glimchb** [linux-nvme/libnvme#268]
**This works fine:** ( using pre-installed packages and skips meson subprojects) 
```
docker build https://github.com/linux-nvme/libnvme.git#master -f-<<EOF
FROM fedora:33
RUN dnf install -y gcc g++ cmake libuuid-devel swig python-devel meson
RUN dnf install -y openssl-devel json-c-devel
WORKDIR /root
COPY . .
RUN meson .build && ninja -C .build && meson install -C .build
EOF
```
**This fails:**  ( uses meson subprojects instead of pre-installed packages) 
```
docker build https://github.com/linux-nvme/libnvme.git#master -f-<<EOF
FROM fedora:33
RUN dnf install -y gcc g++ cmake libuuid-devel swig python-devel meson
WORKDIR /root
COPY . .
RUN meson .build && ninja -C .build && meson install -C .build
EOF
```
**With this error:** (looks like installation stage)
```
[753/754] Compiling C object libnvme/_nvme.cpython-39-x86_64-linux-gnu.so.p/meson-generated_.._nvme_wrap.c.o
[754/754] Linking target libnvme/_nvme.cpython-39-x86_64-linux-gnu.so
ninja: Entering directory `/root/.build'
ninja: no work to do.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 228, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 720, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 512, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 615, in install_targets
    raise RuntimeError(f'File {t.fname!r} could not be found')
RuntimeError: File 'subprojects/openssl-1.1.1l/openssl' could not be found
Installing subprojects/json-c-0.15/libjson-c.so to /usr/lib64
Installing subprojects/openssl-1.1.1l/libcrypto.so to /usr/lib64
Installing subprojects/openssl-1.1.1l/libssl.so to /usr/lib64
The command '/bin/sh -c meson .build && ninja -C .build && meson install -C .build' returned a non-zero code: 2
```

I can't figure out what is missing during compile stage that fails during installation...

**Comment by igaw** [comment]
Setting `install: false` seems to do the trick for me. The question here what should happen if `build_by_default: false` and `install: true` is set. I haven't found anything related to this in https://mesonbuild.com/Reference-manual_functions.html#executable I think we need to ask the meson project what's the right to do here.

**Comment by glimchb** [comment]
I found this small hint https://github.com/mesonbuild/meson/blob/master/docs/yaml/functions/custom_target.yaml#L73
```
      *(since 0.50.0)* If `build_by_default` is explicitly set to false, `install`
      will no longer override it. If `build_by_default` is not set, `install` will
      still determine its default.
```

**Comment by igaw** [comment]
https://github.com/mesonbuild/meson/issues/4370

**Comment by igaw** [comment]
There are two workarounds until we figure out how to fix it properly:
- either patch meson.build
- build the openssl binary and install it alongside
I think the second approach is better.

**Comment by glimchb** [comment]
@igaw I also experimented with this commit to test this use case in CI https://github.com/glimchb/libnvme/commit/0cd38cb6b93be6b992b299b905e3684aa9aa7323

**Comment by glimchb** [comment]
@igaw the fix is not working see
```
$ docker build https://github.com/linux-nvme/libnvme.git#master -f-<<EOF
FROM fedora:33
RUN dnf install -y gcc g++ cmake libuuid-devel swig python-devel meson
#RUN dnf install -y openssl-devel json-c-devel
RUN update-ca-trust
WORKDIR /root
COPY . .
RUN meson .build && ninja -C .build && meson install -C .build
```
error
```
[753/754] Compiling C object libnvme/_nvme.cpython-39-x86_64-linux-gnu.so.p/meson-generated_.._nvme_wrap.c.o
[754/754] Linking target libnvme/_nvme.cpython-39-x86_64-linux-gnu.so
ninja: Entering directory `/root/.build'
ninja: no work to do.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 228, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 720, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 512, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 615, in install_targets
    raise RuntimeError(f'File {t.fname!r} could not be found')
RuntimeError: File 'subprojects/openssl-1.1.1l/openssl' could not be found
Installing subprojects/json-c-0.15/libjson-c.so to /usr/lib64
Installing subprojects/openssl-1.1.1l/libcrypto.so to /usr/lib64
Installing subprojects/openssl-1.1.1l/libssl.so to /usr/lib64
The command '/bin/sh -c meson .build && ninja -C .build && meson install -C .build' returned a non-zero code: 2
```

**Comment by igaw** [comment]
I've tested it locally and it worked fine. Are you sure you have an updated version of libnvme?

**Comment by glimchb** [comment]
sure, I built directly from github to be extra sure `docker build https://github.com/linux-nvme/libnvme.git#master`

**Comment by igaw** [comment]
workaround: `meson .build && ninja -C .build && ninja -C .build openssl && meson install -C .build`

**Comment by glimchb** [comment]
another workaround: `meson .build && ninja -C .build && meson install -C .build --skip-subprojects=openssl`

**Comment by glimchb** [comment]
Should be fixed by https://github.com/mesonbuild/wrapdb/pull/297
